
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost/event}
    username: "postgres"
    password: "docker"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'


